INSERT INTO companies (company_name, ats, career_url, ats_config, industry) VALUES
('Webflow', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/webflow/jobs', '{"slug":"webflow"}', 'SaaS - Productivity'),
('PandaDoc', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/pandadoc/jobs', '{"slug":"pandadoc"}', 'SaaS - Enterprise'),
('Calendly', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/calendly/jobs', '{"slug":"calendly"}', 'SaaS - Productivity'),
('Dropbox', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/dropbox/jobs', '{"slug":"dropbox"}', 'SaaS - Productivity'),
('Ping Identity', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/pingidentity/jobs', '{"slug":"pingidentity"}', 'SaaS - Enterprise'),
('HubSpot', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/hubspot/jobs', '{"slug":"hubspot"}', 'SaaS - Enterprise'),
('Intercom', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/intercom/jobs', '{"slug":"intercom"}', 'SaaS - Enterprise'),
('Smartsheet', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/smartsheet/jobs', '{"slug":"smartsheet"}', 'SaaS - Productivity'),
('Okta', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/okta/jobs', '{"slug":"okta"}', 'SaaS - Enterprise'),
('PagerDuty', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/pagerduty/jobs', '{"slug":"pagerduty"}', 'Dev Tools / Infra'),
('Zscaler', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/zscaler/jobs', '{"slug":"zscaler"}', 'SaaS - Enterprise'),
('New Relic', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/newrelic/jobs', '{"slug":"newrelic"}', 'Dev Tools / Infra'),
('GitLab', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/gitlab/jobs', '{"slug":"gitlab"}', 'Dev Tools / Infra'),
('Cloudflare', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/cloudflare/jobs', '{"slug":"cloudflare"}', 'Cybersecurity'),
('Twilio', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/twilio/jobs', '{"slug":"twilio"}', 'Dev Tools / Infra'),
('Elastic', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/elastic/jobs', '{"slug":"elastic"}', 'Dev Tools / Infra'),
('Datadog', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/datadog/jobs', '{"slug":"datadog"}', 'Dev Tools / Infra'),
('PlanetScale', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/planetscale/jobs', '{"slug":"planetscale"}', 'Dev Tools / Infra'),
('Postman', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/postman/jobs', '{"slug":"postman"}', 'Dev Tools / Infra'),
('Stability AI', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/stabilityai/jobs', '{"slug":"stabilityai"}', 'AI / Dev Tools'),
('CircleCI', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/circleci/jobs', '{"slug":"circleci"}', 'Dev Tools / Infra'),
('JFrog', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/jfrog/jobs', '{"slug":"jfrog"}', 'Dev Tools / Infra'),
('MongoDB', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/mongodb/jobs', '{"slug":"mongodb"}', 'Dev Tools / Infra'),
('Databricks', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/databricks/jobs', '{"slug":"databricks"}', 'Dev Tools / Infra'),
('Inflection AI', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/inflectionai/jobs', '{"slug":"inflectionai"}', 'AI / Dev Tools'),
('Together AI', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/togetherai/jobs', '{"slug":"togetherai"}', 'AI / Dev Tools'),
('Netlify', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/netlify/jobs', '{"slug":"netlify"}', 'Dev Tools / Infra'),
('Coinbase', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/coinbase/jobs', '{"slug":"coinbase"}', 'Fintech'),
('SoFi', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/sofi/jobs', '{"slug":"sofi"}', 'Fintech'),
('Bill.com', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/billcom/jobs', '{"slug":"billcom"}', 'Fintech'),
('Betterment', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/betterment/jobs', '{"slug":"betterment"}', 'Fintech'),
('Marqeta', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/marqeta/jobs', '{"slug":"marqeta"}', 'Fintech'),
('Upstart', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/upstart/jobs', '{"slug":"upstart"}', 'Fintech'),
('Current', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/current/jobs', '{"slug":"current"}', 'Fintech'),
('Toast', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/toast/jobs', '{"slug":"toast"}', 'Fintech'),
('N26', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/n26/jobs', '{"slug":"n26"}', 'Fintech'),
('Nextdoor', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/nextdoor/jobs', '{"slug":"nextdoor"}', 'Consumer Apps'),
('Peloton', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/peloton/jobs', '{"slug":"peloton"}', 'Consumer Apps'),
('Instacart', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/instacart/jobs', '{"slug":"instacart"}', 'Consumer Apps'),
('Pinterest', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/pinterest/jobs', '{"slug":"pinterest"}', 'Consumer Apps'),
('Remote.com', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/remotecom/jobs', '{"slug":"remotecom"}', 'Fintech'),
('TripAdvisor', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/tripadvisor/jobs', '{"slug":"tripadvisor"}', 'Consumer Apps'),
('StockX', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/stockx/jobs', '{"slug":"stockx"}', 'Consumer Apps'),
('Faire', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/faire/jobs', '{"slug":"faire"}', 'Consumer Apps'),
('Poshmark', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/poshmark/jobs', '{"slug":"poshmark"}', 'Consumer Apps'),
('Cerebral', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/cerebral/jobs', '{"slug":"cerebral"}', 'Healthcare'),
('Talkspace', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/talkspace/jobs', '{"slug":"talkspace"}', 'Healthcare'),
('Maven Clinic', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/mavenclinic/jobs', '{"slug":"mavenclinic"}', 'Healthcare'),
('Forward', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/forward/jobs', '{"slug":"forward"}', 'Healthcare'),
('Clover Health', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/cloverhealth/jobs', '{"slug":"cloverhealth"}', 'Healthcare'),
('Tia', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/tia/jobs', '{"slug":"tia"}', 'Healthcare'),
('BetterHelp', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/betterhelp/jobs', '{"slug":"betterhelp"}', 'Healthcare'),
('Coursera', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/coursera/jobs', '{"slug":"coursera"}', 'Edtech'),
('2U', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/2u/jobs', '{"slug":"2u"}', 'Edtech'),
('Udemy', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/udemy/jobs', '{"slug":"udemy"}', 'Edtech'),
('MasterClass', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/masterclass/jobs', '{"slug":"masterclass"}', 'Edtech'),
('Outschool', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/outschool/jobs', '{"slug":"outschool"}', 'Edtech'),
('Degreed', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/degreed/jobs', '{"slug":"degreed"}', 'Edtech'),
('Skillsoft', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/skillsoft/jobs', '{"slug":"skillsoft"}', 'Edtech'),
('Klaviyo', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/klaviyo/jobs', '{"slug":"klaviyo"}', 'E-commerce'),
('Squarespace', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/squarespace/jobs', '{"slug":"squarespace"}', 'E-commerce'),
('Khan Academy', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/khanacademy/jobs', '{"slug":"khanacademy"}', 'Edtech'),
('Flexport', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/flexport/jobs', '{"slug":"flexport"}', 'E-commerce'),
('Indeed', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/indeed/jobs', '{"slug":"indeed"}', 'Marketplaces'),
('Glassdoor', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/glassdoor/jobs', '{"slug":"glassdoor"}', 'Marketplaces'),
('Upwork', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/upwork/jobs', '{"slug":"upwork"}', 'Marketplaces'),
('TaskRabbit', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/taskrabbit/jobs', '{"slug":"taskrabbit"}', 'Marketplaces'),
('LinkedIn', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/linkedin/jobs', '{"slug":"linkedin"}', 'Marketplaces'),
('ZipRecruiter', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/ziprecruiter/jobs', '{"slug":"ziprecruiter"}', 'Marketplaces'),
('OpenTable', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/opentable/jobs', '{"slug":"opentable"}', 'Marketplaces'),
('Affinity', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/affinity/jobs', '{"slug":"affinity"}', 'Marketplaces'),
('HomeLight', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/homelight/jobs', '{"slug":"homelight"}', 'Real Estate'),
('FourKites', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/fourkites/jobs', '{"slug":"fourkites"}', 'Logistics'),
('project44', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/project44/jobs', '{"slug":"project44"}', 'Logistics'),
('Lattice', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/lattice/jobs', '{"slug":"lattice"}', 'SaaS - HR Tech'),
('Motive', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/motive/jobs', '{"slug":"motive"}', 'IoT / Logistics'),
('ClickHouse', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/clickhouse/jobs', '{"slug":"clickhouse"}', 'Dev Tools / Infra'),
('Samsara', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/samsara/jobs', '{"slug":"samsara"}', 'IoT / Logistics'),
('Greenhouse', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/greenhouse/jobs', '{"slug":"greenhouse"}', 'SaaS - HR Tech'),
('Fivetran', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/fivetran/jobs', '{"slug":"fivetran"}', 'Dev Tools / Infra'),
('Workato', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/workato/jobs', '{"slug":"workato"}', 'SaaS - Enterprise'),
('Pendo', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/pendo/jobs', '{"slug":"pendo"}', 'Data / Analytics'),
('Culture Amp', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/cultureamp/jobs', '{"slug":"cultureamp"}', 'SaaS - HR Tech'),
('LaunchDarkly', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/launchdarkly/jobs', '{"slug":"launchdarkly"}', 'Dev Tools / Infra'),
('Amplitude', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/amplitude/jobs', '{"slug":"amplitude"}', 'Data / Analytics'),
('Mixpanel', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/mixpanel/jobs', '{"slug":"mixpanel"}', 'Data / Analytics'),
('Iterable', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/iterable/jobs', '{"slug":"iterable"}', 'Marketing Tech'),
('Sigma Computing', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/sigmacomputing/jobs', '{"slug":"sigmacomputing"}', 'Data / Analytics'),
('Braze', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/braze/jobs', '{"slug":"braze"}', 'Marketing Tech'),
('Attentive', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/attentive/jobs', '{"slug":"attentive"}', 'Marketing Tech'),
('Postscript', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/postscript/jobs', '{"slug":"postscript"}', 'Marketing Tech'),
('Constant Contact', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/constantcontact/jobs', '{"slug":"constantcontact"}', 'Marketing Tech'),
('ZoomInfo', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/zoominfo/jobs', '{"slug":"zoominfo"}', 'Sales Tech'),
('Apollo.io', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/apolloio/jobs', '{"slug":"apolloio"}', 'Sales Tech'),
('One Medical', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/onemedical/jobs', '{"slug":"onemedical"}', 'Healthcare'),
('Customer.io', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/customerio/jobs', '{"slug":"customerio"}', 'Marketing Tech'),
('Otter.ai', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/otterai/jobs', '{"slug":"otterai"}', 'SaaS - Productivity'),
('Superhuman', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/superhuman', '{"slug":"superhuman"}', 'SaaS - Productivity'),
('ClickUp', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/clickup', '{"slug":"clickup"}', 'SaaS - Productivity'),
('Snyk', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/snyk', '{"slug":"snyk"}', 'Cybersecurity'),
('Wiz', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/wiz', '{"slug":"wiz"}', 'Cybersecurity'),
('1Password', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/1password', '{"slug":"1password"}', 'Cybersecurity'),
('Confluent', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/confluent', '{"slug":"confluent"}', 'Dev Tools / Infra'),
('Vercel', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/vercel', '{"slug":"vercel"}', 'Dev Tools / Infra'),
('Pinecone', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/pinecone', '{"slug":"pinecone"}', 'AI / Dev Tools'),
('Runway', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/runway', '{"slug":"runway"}', 'AI / Dev Tools'),
('Kraken', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/kraken', '{"slug":"kraken"}', 'Fintech'),
('Render', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/render', '{"slug":"render"}', 'Dev Tools / Infra'),
('Deel', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/deel', '{"slug":"deel"}', 'Fintech'),
('Snowflake', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/snowflake', '{"slug":"snowflake"}', 'Dev Tools / Infra'),
('Supabase', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/supabase', '{"slug":"supabase"}', 'Dev Tools / Infra'),
('LangChain', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/langchain', '{"slug":"langchain"}', 'AI / Dev Tools'),
('Sierra', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/sierra', '{"slug":"sierra"}', 'AI / Dev Tools'),
('Plaid', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/plaid', '{"slug":"plaid"}', 'Fintech'),
('Replit', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/replit', '{"slug":"replit"}', 'AI / Dev Tools'),
('Cohere', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/cohere', '{"slug":"cohere"}', 'AI / Dev Tools'),
('Bumble', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/bumble', '{"slug":"bumble"}', 'Consumer Apps'),
('Thumbtack', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/thumbtack', '{"slug":"thumbtack"}', 'Consumer Apps'),
('Angi', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/angi', '{"slug":"angi"}', 'Consumer Apps'),
('Strava', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/strava', '{"slug":"strava"}', 'Consumer Apps'),
('Bolt', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/bolt', '{"slug":"bolt"}', 'E-commerce'),
('Recharge', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/recharge', '{"slug":"recharge"}', 'E-commerce'),
('Carbon Health', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/carbonhealth', '{"slug":"carbonhealth"}', 'Healthcare'),
('Drata', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/drata', '{"slug":"drata"}', 'SaaS - Enterprise'),
('FullStory', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/fullstory', '{"slug":"fullstory"}', 'Data / Analytics'),
('Airbyte', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/airbyte', '{"slug":"airbyte"}', 'Dev Tools / Infra'),
('Statsig', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/statsig', '{"slug":"statsig"}', 'Dev Tools / Infra'),
('Temporal', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/temporal', '{"slug":"temporal"}', 'Dev Tools / Infra'),
('Zapier', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/zapier', '{"slug":"zapier"}', 'SaaS - Enterprise'),
('Vanta', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/vanta', '{"slug":"vanta"}', 'SaaS - Enterprise'),
('Wealthfront', 'lever', 'https://api.lever.co/v0/postings/wealthfront', '{"slug":"wealthfront"}', 'Fintech'),
('Houzz', 'lever', 'https://api.lever.co/v0/postings/houzz', '{"slug":"houzz"}', 'Consumer Apps'),
('Ro', 'lever', 'https://api.lever.co/v0/postings/ro', '{"slug":"ro"}', 'Healthcare'),
('Match Group', 'lever', 'https://api.lever.co/v0/postings/matchgroup', '{"slug":"matchgroup"}', 'Consumer Apps'),
('Included Health', 'lever', 'https://api.lever.co/v0/postings/includedhealth', '{"slug":"includedhealth"}', 'Healthcare'),
('Rover', 'lever', 'https://api.lever.co/v0/postings/rover', '{"slug":"rover"}', 'Marketplaces'),
('Secureframe', 'lever', 'https://api.lever.co/v0/postings/secureframe', '{"slug":"secureframe"}', 'SaaS - Enterprise'),
('Outreach', 'lever', 'https://api.lever.co/v0/postings/outreach', '{"slug":"outreach"}', 'Sales Tech'),
('ActiveCampaign', 'lever', 'https://api.lever.co/v0/postings/activecampaign', '{"slug":"activecampaign"}', 'Marketing Tech'),
('Gopuff', 'lever', 'https://api.lever.co/v0/postings/gopuff', '{"slug":"gopuff"}', 'Marketplaces'),
('Gusto', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/gusto/jobs', '{"slug":"gusto"}', 'Fintech'),
('Navan', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/tripactions/jobs', '{"slug":"tripactions"}', 'Fintech'),
('Harvey AI', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/harvey', '{"slug":"harvey"}', 'AI / Dev Tools'),
('Oscar Health', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/oscar/jobs', '{"slug":"oscar"}', 'Healthcare'),
('Make (Integromat)', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/make/jobs', '{"slug":"make"}', 'SaaS - Enterprise');