INSERT INTO companies (company_name, ats, career_url, ats_config, industry) VALUES
('DoubleVerify', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/doubleverify/jobs', '{"slug":"doubleverify"}', 'AdTech'),
('The Trade Desk', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/thetradedesk/jobs', '{"slug":"thetradedesk"}', 'AdTech'),
('Scopely', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/scopely/jobs', '{"slug":"scopely"}', 'Gaming'),
('Vonage', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/vonage/jobs', '{"slug":"vonage"}', 'Communications'),
('Discord', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/discord/jobs', '{"slug":"discord"}', 'Consumer Apps'),
('Dialpad', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/dialpad/jobs', '{"slug":"dialpad"}', 'Communications'),
('Twitch', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/twitch/jobs', '{"slug":"twitch"}', 'Gaming / Streaming'),
('AppLovin', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/applovin/jobs', '{"slug":"applovin"}', 'AdTech / Gaming'),
('Roblox', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/roblox/jobs', '{"slug":"roblox"}', 'Gaming'),
('Mindbody', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/mindbody/jobs', '{"slug":"mindbody"}', 'SMB SaaS'),
('Riot Games', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/riotgames/jobs', '{"slug":"riotgames"}', 'Gaming'),
('ClassPass', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/classpass/jobs', '{"slug":"classpass"}', 'SMB SaaS'),
('Alloy', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/alloy/jobs', '{"slug":"alloy"}', 'Identity / Compliance'),
('Rocket Lawyer', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/rocketlawyer/jobs', '{"slug":"rocketlawyer"}', 'Legal Tech'),
('Roku', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/roku/jobs', '{"slug":"roku"}', 'Streaming'),
('Forter', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/forter/jobs', '{"slug":"forter"}', 'Fraud / Risk'),
('Riskified', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/riskified/jobs', '{"slug":"riskified"}', 'Fraud / Risk'),
('Consensys', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/consensys/jobs', '{"slug":"consensys"}', 'Crypto'),
('Fireblocks', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/fireblocks/jobs', '{"slug":"fireblocks"}', 'Crypto'),
('Gemini', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/gemini/jobs', '{"slug":"gemini"}', 'Crypto'),
('Waymo', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/waymo/jobs', '{"slug":"waymo"}', 'Automotive / AI'),
('ChargePoint', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/chargepoint/jobs', '{"slug":"chargepoint"}', 'Energy'),
('Aurora Innovation', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/aurorainnovation/jobs', '{"slug":"aurorainnovation"}', 'Automotive / AI'),
('Lucid Motors', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/lucidmotors/jobs', '{"slug":"lucidmotors"}', 'Automotive / Energy'),
('Komodo Health', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/komodohealth/jobs', '{"slug":"komodohealth"}', 'Healthtech'),
('Oura', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/oura/jobs', '{"slug":"oura"}', 'Wearables'),
('Newsela', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/newsela/jobs', '{"slug":"newsela"}', 'Edtech'),
('Flatiron Health', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/flatironhealth/jobs', '{"slug":"flatironhealth"}', 'Healthtech'),
('IXL Learning', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/ixllearning/jobs', '{"slug":"ixllearning"}', 'Edtech'),
('Epic Games', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/epicgames/jobs', '{"slug":"epicgames"}', 'Gaming'),
('General Assembly', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/generalassembly/jobs', '{"slug":"generalassembly"}', 'Edtech'),
('Springboard', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/springboard/jobs', '{"slug":"springboard"}', 'Edtech'),
('Highnote', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/highnote/jobs', '{"slug":"highnote"}', 'Fintech'),
('Course Hero', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/coursehero/jobs', '{"slug":"coursehero"}', 'Edtech'),
('Wonderschool', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/wonderschool/jobs', '{"slug":"wonderschool"}', 'Edtech'),
('Lithic', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/lithic/jobs', '{"slug":"lithic"}', 'Fintech'),
('DataCamp', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/datacamp/jobs', '{"slug":"datacamp"}', 'Edtech'),
('Knock', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/knock/jobs', '{"slug":"knock"}', 'Dev Tools / Infra'),
('Warp', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/warp/jobs', '{"slug":"warp"}', 'Dev Tools / Infra'),
('CoreWeave', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/coreweave/jobs', '{"slug":"coreweave"}', 'AI / Dev Tools'),
('Fireworks AI', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/fireworksai/jobs', '{"slug":"fireworksai"}', 'AI / Dev Tools'),
('Descript', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/descript/jobs', '{"slug":"descript"}', 'Creator Tools'),
('Range', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/range/jobs', '{"slug":"range"}', 'SaaS - Productivity'),
('Aha!', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/aha/jobs', '{"slug":"aha"}', 'SaaS - Productivity'),
('HeyGen', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/heygen/jobs', '{"slug":"heygen"}', 'AI / Creator Tools'),
('Udio', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/udio/jobs', '{"slug":"udio"}', 'AI / Creator Tools'),
('Lex', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/lex/jobs', '{"slug":"lex"}', 'AI / Creator Tools'),
('Typeface', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/typeface/jobs', '{"slug":"typeface"}', 'AI / Marketing'),
('6sense', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/6sense/jobs', '{"slug":"6sense"}', 'Marketing Tech'),
('Pleo', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/pleo/jobs', '{"slug":"pleo"}', 'Fintech'),
('Array', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/array/jobs', '{"slug":"array"}', 'Fintech'),
('Earnin', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/earnin/jobs', '{"slug":"earnin"}', 'Fintech'),
('Cleo', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/cleo/jobs', '{"slug":"cleo"}', 'Fintech'),
('Kustomer', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/kustomer', '{"slug":"kustomer"}', 'Customer Support'),
('Niantic', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/niantic', '{"slug":"niantic"}', 'Gaming'),
('Substack', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/substack', '{"slug":"substack"}', 'Creator Economy'),
('Persona', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/persona', '{"slug":"persona"}', 'Identity / Compliance'),
('Patreon', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/patreon', '{"slug":"patreon"}', 'Creator Economy'),
('Help Scout', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/helpscout', '{"slug":"helpscout"}', 'Customer Support'),
('Sift', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/sift', '{"slug":"sift"}', 'Fraud / Risk'),
('Chili Piper', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/chilipiper', '{"slug":"chilipiper"}', 'Sales Tech'),
('Podium', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/podium', '{"slug":"podium"}', 'SMB SaaS'),
('OpenSea', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/opensea', '{"slug":"opensea"}', 'Crypto'),
('Sardine', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/sardine', '{"slug":"sardine"}', 'Fraud / Risk'),
('Socure', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/socure', '{"slug":"socure"}', 'Identity / Compliance'),
('Span', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/span', '{"slug":"span"}', 'Energy'),
('Color Health', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/color-health', '{"slug":"color-health"}', 'Healthtech'),
('Magic Eden', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/magiceden', '{"slug":"magiceden"}', 'Crypto'),
('Levels', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/levels', '{"slug":"levels"}', 'Health'),
('Abridge', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/abridge', '{"slug":"abridge"}', 'Healthtech'),
('Brainly', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/brainly', '{"slug":"brainly"}', 'Edtech'),
('Whoop', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/whoop', '{"slug":"whoop"}', 'Wearables'),
('Stytch', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/stytch', '{"slug":"stytch"}', 'Dev Tools / Infra'),
('Modern Treasury', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/moderntreasury', '{"slug":"moderntreasury"}', 'Fintech'),
('Modal', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/modal', '{"slug":"modal"}', 'Dev Tools / Infra'),
('Resend', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/resend', '{"slug":"resend"}', 'Dev Tools / Infra'),
('Rho', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/rho', '{"slug":"rho"}', 'Fintech'),
('Column', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/column', '{"slug":"column"}', 'Fintech'),
('Handshake', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/handshake', '{"slug":"handshake"}', 'Edtech / Recruiting'),
('Trigger.dev', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/triggerdev', '{"slug":"triggerdev"}', 'Dev Tools / Infra'),
('WorkOS', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/workos', '{"slug":"workos"}', 'Dev Tools / Infra'),
('ClassDojo', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/classdojo', '{"slug":"classdojo"}', 'Edtech'),
('Shield AI', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/shield-ai', '{"slug":"shield-ai"}', 'Defense Tech'),
('Synctera', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/synctera', '{"slug":"synctera"}', 'Fintech'),
('Baseten', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/baseten', '{"slug":"baseten"}', 'AI / Dev Tools'),
('Clerk', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/clerk', '{"slug":"clerk"}', 'Dev Tools / Infra'),
('Inngest', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/inngest', '{"slug":"inngest"}', 'Dev Tools / Infra'),
('Unit', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/unit', '{"slug":"unit"}', 'Fintech'),
('Anyscale', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/anyscale', '{"slug":"anyscale"}', 'AI / Dev Tools'),
('Neon', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/neon', '{"slug":"neon"}', 'Dev Tools / Infra'),
('Raycast', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/raycast', '{"slug":"raycast"}', 'SaaS - Productivity'),
('Railway', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/railway', '{"slug":"railway"}', 'Dev Tools / Infra'),
('Tavus', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/tavus', '{"slug":"tavus"}', 'AI / Creator Tools'),
('Synthesia', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/synthesia', '{"slug":"synthesia"}', 'AI / Creator Tools'),
('Midjourney', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/midjourney', '{"slug":"midjourney"}', 'AI / Creator Tools'),
('ElevenLabs', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/elevenlabs', '{"slug":"elevenlabs"}', 'AI / Creator Tools'),
('Writer', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/writer', '{"slug":"writer"}', 'AI / Marketing'),
('Ideogram', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/ideogram', '{"slug":"ideogram"}', 'AI / Creator Tools'),
('Mutiny', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/mutiny', '{"slug":"mutiny"}', 'Marketing Tech'),
('Demandbase', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/demandbase', '{"slug":"demandbase"}', 'Marketing Tech'),
('Endgame', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/endgame', '{"slug":"endgame"}', 'Marketing Tech'),
('Suno', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/suno', '{"slug":"suno"}', 'AI / Creator Tools'),
('Common Room', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/commonroom', '{"slug":"commonroom"}', 'Marketing Tech'),
('Levelpath', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/levelpath', '{"slug":"levelpath"}', 'SaaS - Procurement'),
('Cerebras', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/cerebras', '{"slug":"cerebras"}', 'AI / Dev Tools'),
('Zip', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/zip', '{"slug":"zip"}', 'SaaS - Procurement'),
('Spendesk', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/spendesk', '{"slug":"spendesk"}', 'Fintech'),
('Codat', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/codat', '{"slug":"codat"}', 'Fintech'),
('Parafin', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/parafin', '{"slug":"parafin"}', 'Fintech'),
('Middesk', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/middesk', '{"slug":"middesk"}', 'Identity / Compliance'),
('Luma AI', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/lumaai', '{"slug":"lumaai"}', 'AI / Creator Tools'),
('Atomic', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/atomic', '{"slug":"atomic"}', 'Fintech'),
('Belvo', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/belvo', '{"slug":"belvo"}', 'Fintech'),
('Capchase', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/capchase', '{"slug":"capchase"}', 'Fintech'),
('Footprint', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/footprint', '{"slug":"footprint"}', 'Identity / Compliance'),
('Dave', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/dave', '{"slug":"dave"}', 'Fintech'),
('Brigit', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/brigit', '{"slug":"brigit"}', 'Fintech'),
('Monarch Money', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/monarchmoney', '{"slug":"monarchmoney"}', 'Fintech'),
('Copilot Money', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/copilot-money', '{"slug":"copilot-money"}', 'Fintech'),
('Possible Finance', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/possible-finance', '{"slug":"possible-finance"}', 'Fintech'),
('Highspot', 'lever', 'https://api.lever.co/v0/postings/highspot', '{"slug":"highspot"}', 'Sales Tech'),
('Aircall', 'lever', 'https://api.lever.co/v0/postings/aircall', '{"slug":"aircall"}', 'Customer Support'),
('Fresha', 'lever', 'https://api.lever.co/v0/postings/fresha', '{"slug":"fresha"}', 'SMB SaaS'),
('Arcadia', 'lever', 'https://api.lever.co/v0/postings/arcadia', '{"slug":"arcadia"}', 'Energy'),
('Articulate', 'lever', 'https://api.lever.co/v0/postings/articulate', '{"slug":"articulate"}', 'Edtech'),
('Zoox', 'lever', 'https://api.lever.co/v0/postings/zoox', '{"slug":"zoox"}', 'Automotive / AI'),
('Palantir', 'lever', 'https://api.lever.co/v0/postings/palantir', '{"slug":"palantir"}', 'Data / Defense'),
('Kapwing', 'lever', 'https://api.lever.co/v0/postings/kapwing', '{"slug":"kapwing"}', 'Creator Tools'),
('Uniswap Labs', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/uniswap', '{"slug":"uniswap"}', 'Crypto');