-- Activate Workday companies whose guessed tenant slug verified OK
-- Site chosen = board with most live jobs on the tenant

UPDATE companies SET active = true, ats_config = '{"tenant": "3m", "instance": "wd1", "site": "Search"}'::jsonb WHERE company_name = '3M' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "aig", "instance": "wd1", "site": "aig"}'::jsonb WHERE company_name = 'AIG' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "asml", "instance": "wd3", "site": "ASMLBERLIN"}'::jsonb WHERE company_name = 'ASML' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "agilent", "instance": "wd5", "site": "Agilent_Careers"}'::jsonb WHERE company_name = 'Agilent' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "allstate", "instance": "wd5", "site": "allstate_careers"}'::jsonb WHERE company_name = 'Allstate' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "ameriprise", "instance": "wd5", "site": "Ameriprise"}'::jsonb WHERE company_name = 'Ameriprise Financial' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "astrazeneca", "instance": "wd3", "site": "Careers"}'::jsonb WHERE company_name = 'AstraZeneca' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "atmosenergy", "instance": "wd108", "site": "External_Career_Site"}'::jsonb WHERE company_name = 'Atmos Energy' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "autodesk", "instance": "wd1", "site": "Ext"}'::jsonb WHERE company_name = 'Autodesk' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "blackrock", "instance": "wd1", "site": "BlackRock_Professional"}'::jsonb WHERE company_name = 'BlackRock' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "broadcom", "instance": "wd1", "site": "External_Career"}'::jsonb WHERE company_name = 'Broadcom' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "cibc", "instance": "wd3", "site": "search"}'::jsonb WHERE company_name = 'CIBC' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "cmegroup", "instance": "wd1", "site": "cme_careers"}'::jsonb WHERE company_name = 'CME Group' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "cardinalhealth", "instance": "wd1", "site": "EXT"}'::jsonb WHERE company_name = 'Cardinal Health' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "carrier", "instance": "wd5", "site": "jobs"}'::jsonb WHERE company_name = 'Carrier Global' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "cboe", "instance": "wd1", "site": "External_Career_CBOE"}'::jsonb WHERE company_name = 'Cboe Global Markets' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "cenovus", "instance": "wd3", "site": "careers"}'::jsonb WHERE company_name = 'Cenovus Energy' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "chevron", "instance": "wd5", "site": "jobs"}'::jsonb WHERE company_name = 'Chevron' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "chipotle", "instance": "wd5", "site": "ChipotleCareers"}'::jsonb WHERE company_name = 'Chipotle' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "cisco", "instance": "wd5", "site": "Cisco_Careers"}'::jsonb WHERE company_name = 'Cisco' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "copart", "instance": "wd12", "site": "Copart"}'::jsonb WHERE company_name = 'Copart' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "dexcom", "instance": "wd1", "site": "Dexcom"}'::jsonb WHERE company_name = 'DexCom' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "diamondbackenergy", "instance": "wd12", "site": "DBE"}'::jsonb WHERE company_name = 'Diamondback Energy' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "echostar", "instance": "wd501", "site": "echostar"}'::jsonb WHERE company_name = 'EchoStar' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "edwards", "instance": "wd5", "site": "EdwardsCareers"}'::jsonb WHERE company_name = 'Edwards Lifesciences' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "emerson", "instance": "wd5", "site": "Emerson_College_Staff"}'::jsonb WHERE company_name = 'Emerson Electric' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "enbridge", "instance": "wd3", "site": "enbridge_careers"}'::jsonb WHERE company_name = 'Enbridge' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "extraspace", "instance": "wd5", "site": "ESS_External"}'::jsonb WHERE company_name = 'Extra Space Storage' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "fedex", "instance": "wd1", "site": "FXE-EU_External"}'::jsonb WHERE company_name = 'FedEx' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "ferguson", "instance": "wd1", "site": "Ferguson_Experienced"}'::jsonb WHERE company_name = 'Ferguson' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "fifththird", "instance": "wd5", "site": "53careers"}'::jsonb WHERE company_name = 'Fifth Third Bancorp' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "fiserv", "instance": "wd5", "site": "EXT"}'::jsonb WHERE company_name = 'Fiserv' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "gevernova", "instance": "wd5", "site": "Vernova_ExternalSite"}'::jsonb WHERE company_name = 'GE Vernova' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "gsk", "instance": "wd5", "site": "GSKCareers"}'::jsonb WHERE company_name = 'GSK' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "generalmotors", "instance": "wd5", "site": "Careers_GM"}'::jsonb WHERE company_name = 'General Motors' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "thehartford", "instance": "wd5", "site": "Careers_External"}'::jsonb WHERE company_name = 'Hartford Insurance' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "ing", "instance": "wd3", "site": "ICSGBLCOR"}'::jsonb WHERE company_name = 'ING Groep' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "intuitive", "instance": "wd1", "site": "irtc_careers"}'::jsonb WHERE company_name = 'Intuitive Surgical' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "ironmountain", "instance": "wd5", "site": "iron-mountain-jobs"}'::jsonb WHERE company_name = 'Iron Mountain' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "kimberlyclark", "instance": "wd1", "site": "GLOBAL"}'::jsonb WHERE company_name = 'Kimberly-Clark' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "sands", "instance": "wd1", "site": "sands_careers"}'::jsonb WHERE company_name = 'Las Vegas Sands' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "mtb", "instance": "wd5", "site": "MTB"}'::jsonb WHERE company_name = 'M&T Bank' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "mpc", "instance": "wd1", "site": "MPCCareers"}'::jsonb WHERE company_name = 'MPLX' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "manulife", "instance": "wd3", "site": "MFCJH_Jobs"}'::jsonb WHERE company_name = 'Manulife Financial' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "mpc", "instance": "wd1", "site": "MPCCareers"}'::jsonb WHERE company_name = 'Marathon Petroleum' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "mckesson", "instance": "wd3", "site": "External_Careers"}'::jsonb WHERE company_name = 'McKesson' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "medline", "instance": "wd5", "site": "Medline"}'::jsonb WHERE company_name = 'Medline' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "medtronic", "instance": "wd1", "site": "MedtronicCareers"}'::jsonb WHERE company_name = 'Medtronic' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "nvidia", "instance": "wd5", "site": "NVIDIAExternalCareerSite"}'::jsonb WHERE company_name = 'NVIDIA' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "nxp", "instance": "wd3", "site": "careers"}'::jsonb WHERE company_name = 'NXP Semiconductors' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "nasdaq", "instance": "wd1", "site": "Global_External_Site"}'::jsonb WHERE company_name = 'Nasdaq' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "netflix", "instance": "wd108", "site": "Netflix"}'::jsonb WHERE company_name = 'Netflix' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "pfizer", "instance": "wd1", "site": "PfizerCareers"}'::jsonb WHERE company_name = 'Pfizer' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "prologis", "instance": "wd5", "site": "Prologis_External_Careers"}'::jsonb WHERE company_name = 'Prologis' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "relx", "instance": "wd3", "site": "relx"}'::jsonb WHERE company_name = 'RELX' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "raymondjames", "instance": "wd1", "site": "RaymondJamesCareers"}'::jsonb WHERE company_name = 'Raymond James' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "regeneron", "instance": "wd1", "site": "Careers"}'::jsonb WHERE company_name = 'Regeneron' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "resmed", "instance": "wd3", "site": "ResMed_External_Careers"}'::jsonb WHERE company_name = 'ResMed' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "rocket", "instance": "wd5", "site": "rocket_careers"}'::jsonb WHERE company_name = 'Rocket Companies' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "rockwellautomation", "instance": "wd1", "site": "External_Rockwell_Automation"}'::jsonb WHERE company_name = 'Rockwell Automation' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "sanofi", "instance": "wd3", "site": "SanofiCareers"}'::jsonb WHERE company_name = 'Sanofi' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "simon", "instance": "wd1", "site": "Simon"}'::jsonb WHERE company_name = 'Simon Property' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "sunlife", "instance": "wd3", "site": "Experienced-Jobs"}'::jsonb WHERE company_name = 'Sun Life Financial' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "suncor", "instance": "wd1", "site": "Suncor_External"}'::jsonb WHERE company_name = 'Suncor Energy' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "tcenergy", "instance": "wd3", "site": "CAREER_SITE_TC"}'::jsonb WHERE company_name = 'TC Energy' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "ur", "instance": "wd1", "site": "URcareers"}'::jsonb WHERE company_name = 'United Rentals' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "vrtx", "instance": "wd501", "site": "Vertex_Careers"}'::jsonb WHERE company_name = 'Vertex Pharma' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "disney", "instance": "wd5", "site": "disneycareer"}'::jsonb WHERE company_name = 'Walt Disney' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "wasteconnections", "instance": "wd1", "site": "Careers"}'::jsonb WHERE company_name = 'Waste Connections' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "ebay", "instance": "wd5", "site": "TCGPlayer_External_Career"}'::jsonb WHERE company_name = 'eBay' AND ats = 'workday';
UPDATE companies SET active = true, ats_config = '{"tenant": "nvent", "instance": "wd5", "site": "nVent"}'::jsonb WHERE company_name = 'nVent Electric' AND ats = 'workday';
