INSERT INTO companies (company_name, ats, career_url, ats_config, industry) VALUES
('Homeward', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/homeward/jobs', '{"slug":"homeward"}', 'Real Estate'),
('Tastytrade', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/tastytrade/jobs', '{"slug":"tastytrade"}', 'Fintech'),
('Doma', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/doma/jobs', '{"slug":"doma"}', 'Real Estate'),
('Pacaso', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/pacaso/jobs', '{"slug":"pacaso"}', 'Real Estate'),
('Orchard', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/orchard/jobs', '{"slug":"orchard"}', 'Real Estate'),
('Pie Insurance', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/pieinsurance/jobs', '{"slug":"pieinsurance"}', 'Insurtech'),
('At-Bay', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/atbay/jobs', '{"slug":"atbay"}', 'Insurtech'),
('Roofstock', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/roofstock/jobs', '{"slug":"roofstock"}', 'Real Estate'),
('Coalition', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/coalition/jobs', '{"slug":"coalition"}', 'Insurtech'),
('Alpaca', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/alpaca/jobs', '{"slug":"alpaca"}', 'Fintech'),
('Ethos Life', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/ethoslife/jobs', '{"slug":"ethoslife"}', 'Insurtech'),
('Embroker', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/embroker/jobs', '{"slug":"embroker"}', 'Insurtech'),
('Spin', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/spin/jobs', '{"slug":"spin"}', 'Mobility'),
('Gympass', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/gympass/jobs', '{"slug":"gympass"}', 'Consumer Apps'),
('Cargurus', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/cargurus/jobs', '{"slug":"cargurus"}', 'Marketplaces'),
('Caliber', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/caliber/jobs', '{"slug":"caliber"}', 'Consumer Apps'),
('Bird', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/bird/jobs', '{"slug":"bird"}', 'Mobility'),
('Narvar', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/narvar/jobs', '{"slug":"narvar"}', 'Logistics'),
('Bringg', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/bringg/jobs', '{"slug":"bringg"}', 'Logistics'),
('AfterShip', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/aftership/jobs', '{"slug":"aftership"}', 'Logistics'),
('Flexe', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/flexe/jobs', '{"slug":"flexe"}', 'Logistics'),
('SimpliSafe', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/simplisafe/jobs', '{"slug":"simplisafe"}', 'IoT / Security'),
('Uber Freight', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/uberfreight/jobs', '{"slug":"uberfreight"}', 'Logistics'),
('Found', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/found/jobs', '{"slug":"found"}', 'SMB SaaS'),
('Hover', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/hover/jobs', '{"slug":"hover"}', 'Construction Tech'),
('Fieldwire', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/fieldwire/jobs', '{"slug":"fieldwire"}', 'Construction Tech'),
('VTS', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/vts/jobs', '{"slug":"vts"}', 'Real Estate Tech'),
('CompanyCam', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/companycam/jobs', '{"slug":"companycam"}', 'Construction Tech'),
('Digit', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/digit/jobs', '{"slug":"digit"}', 'Consumer Fintech'),
('Daylight', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/daylight/jobs', '{"slug":"daylight"}', 'Consumer Fintech'),
('Self Financial', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/selffinancial/jobs', '{"slug":"selffinancial"}', 'Consumer Fintech'),
('Credit Karma', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/creditkarma/jobs', '{"slug":"creditkarma"}', 'Consumer Fintech'),
('HelloFresh', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/hellofresh/jobs', '{"slug":"hellofresh"}', 'Foodtech'),
('Slice', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/slice/jobs', '{"slug":"slice"}', 'Foodtech'),
('Thrive Market', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/thrivemarket/jobs', '{"slug":"thrivemarket"}', 'Foodtech'),
('Sweetgreen', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/sweetgreen/jobs', '{"slug":"sweetgreen"}', 'Foodtech'),
('TouchBistro', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/touchbistro/jobs', '{"slug":"touchbistro"}', 'Foodtech'),
('Home Chef', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/homechef/jobs', '{"slug":"homechef"}', 'Foodtech'),
('Misfits Market', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/misfitsmarket/jobs', '{"slug":"misfitsmarket"}', 'Foodtech'),
('Sezzle', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/sezzle/jobs', '{"slug":"sezzle"}', 'Fintech'),
('Tamara', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/tamara/jobs', '{"slug":"tamara"}', 'Fintech'),
('Verkada', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/verkada/jobs', '{"slug":"verkada"}', 'IoT / Security'),
('Justworks', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/justworks/jobs', '{"slug":"justworks"}', 'SaaS - HR Tech'),
('Nectar', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/nectar/jobs', '{"slug":"nectar"}', 'SaaS - HR Tech'),
('Checkr', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/checkr/jobs', '{"slug":"checkr"}', 'SaaS - HR Tech'),
('Sterling', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/sterling/jobs', '{"slug":"sterling"}', 'SaaS - HR Tech'),
('HackerRank', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/hackerrank/jobs', '{"slug":"hackerrank"}', 'SaaS - HR Tech'),
('Globalization Partners', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/globalizationpartners/jobs', '{"slug":"globalizationpartners"}', 'SaaS - HR Tech'),
('Karat', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/karat/jobs', '{"slug":"karat"}', 'SaaS - HR Tech'),
('Turing', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/turing/jobs', '{"slug":"turing"}', 'Marketplaces'),
('Pulley', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/pulley/jobs', '{"slug":"pulley"}', 'Fintech'),
('Built In', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/builtin/jobs', '{"slug":"builtin"}', 'SaaS - HR Tech'),
('EquityZen', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/equityzen/jobs', '{"slug":"equityzen"}', 'Fintech'),
('Ledgy', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/ledgy/jobs', '{"slug":"ledgy"}', 'Fintech'),
('Forge Global', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/forgeglobal/jobs', '{"slug":"forgeglobal"}', 'Fintech'),
('Titan', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/titan', '{"slug":"titan"}', 'Fintech'),
('Branch Insurance', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/branchinsurance', '{"slug":"branchinsurance"}', 'Insurtech'),
('Lemonade', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/lemonade', '{"slug":"lemonade"}', 'Insurtech'),
('Ladder', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/ladder', '{"slug":"ladder"}', 'Insurtech'),
('Bestow', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/bestow', '{"slug":"bestow"}', 'Insurtech'),
('Tonal', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/tonal', '{"slug":"tonal"}', 'Consumer Apps'),
('Newfront', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/newfront', '{"slug":"newfront"}', 'Insurtech'),
('Forto', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/forto', '{"slug":"forto"}', 'Logistics'),
('Arlo', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/arlo', '{"slug":"arlo"}', 'IoT / Security'),
('Latch', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/latch', '{"slug":"latch"}', 'IoT / Smart Home'),
('Curri', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/curri', '{"slug":"curri"}', 'Logistics'),
('Steadily', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/steadily', '{"slug":"steadily"}', 'Real Estate'),
('Novo', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/novo', '{"slug":"novo"}', 'SMB SaaS'),
('HoneyBook', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/honeybook', '{"slug":"honeybook"}', 'SMB SaaS'),
('Acorns', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/acorns', '{"slug":"acorns"}', 'Consumer Fintech'),
('Stash', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/stash', '{"slug":"stash"}', 'Consumer Fintech'),
('GoHenry', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/gohenry', '{"slug":"gohenry"}', 'Consumer Fintech'),
('Greenlight', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/greenlight', '{"slug":"greenlight"}', 'Consumer Fintech'),
('Impossible Foods', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/impossible-foods', '{"slug":"impossible-foods"}', 'Foodtech'),
('Lightspeed', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/lightspeed', '{"slug":"lightspeed"}', 'Foodtech'),
('ZayZoon', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/zayzoon', '{"slug":"zayzoon"}', 'Fintech'),
('Clair', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/clair', '{"slug":"clair"}', 'Fintech'),
('DailyPay', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/dailypay', '{"slug":"dailypay"}', 'Fintech'),
('SpotOn', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/spoton', '{"slug":"spoton"}', 'Foodtech'),
('Leapsome', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/leapsome', '{"slug":"leapsome"}', 'SaaS - HR Tech'),
('Certn', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/certn', '{"slug":"certn"}', 'SaaS - HR Tech'),
('Beamery', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/beamery', '{"slug":"beamery"}', 'SaaS - HR Tech'),
('Andela', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/andela', '{"slug":"andela"}', 'Marketplaces'),
('Loadsmart', 'lever', 'https://api.lever.co/v0/postings/loadsmart', '{"slug":"loadsmart"}', 'Logistics'),
('Veo', 'lever', 'https://api.lever.co/v0/postings/veo', '{"slug":"veo"}', 'Mobility'),
('Loop Returns', 'lever', 'https://api.lever.co/v0/postings/loopreturns', '{"slug":"loopreturns"}', 'Logistics'),
('ChowNow', 'lever', 'https://api.lever.co/v0/postings/chownow', '{"slug":"chownow"}', 'Foodtech'),
('Payactiv', 'lever', 'https://api.lever.co/v0/postings/payactiv', '{"slug":"payactiv"}', 'Fintech'),
('15Five', 'lever', 'https://api.lever.co/v0/postings/15five', '{"slug":"15five"}', 'SaaS - HR Tech'),
('Achievers', 'lever', 'https://api.lever.co/v0/postings/achievers', '{"slug":"achievers"}', 'SaaS - HR Tech'),
('StartEngine', 'lever', 'https://api.lever.co/v0/postings/startengine', '{"slug":"startengine"}', 'Fintech'),
('Toptal', 'lever', 'https://api.lever.co/v0/postings/toptal', '{"slug":"toptal"}', 'Marketplaces'),
('AngelList', 'lever', 'https://api.lever.co/v0/postings/angellist', '{"slug":"angellist"}', 'Marketplaces'),
('Tempo (Fitness)', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/tempo/jobs', '{"slug":"tempo"}', 'Consumer Apps'),
('Root Insurance', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/root/jobs', '{"slug":"root"}', 'Insurtech'),
('Range (Wealth)', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/range/jobs', '{"slug":"range"}', 'Fintech'),
('Future Fit', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/future/jobs', '{"slug":"future"}', 'Consumer Apps'),
('Public.com', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/public/jobs', '{"slug":"public"}', 'Fintech'),
('Kin Insurance', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/kin', '{"slug":"kin"}', 'Insurtech'),
('August Home', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/august', '{"slug":"august"}', 'IoT / Smart Home'),
('Owner.com', 'ashby', 'https://api.ashbyhq.com/posting-api/job-board/owner', '{"slug":"owner"}', 'Foodtech'),
('AngelList Venture', 'lever', 'https://api.lever.co/v0/postings/angellist', '{"slug":"angellist"}', 'Fintech');